### ISSUE TITLE
[svelte-loader] Support Svelte 5

### ISSUE THREAD

**Issue by bhark** [sanity-io/visual-editing#2242] opened 2024-12-02 16:07 UTC
**Is your feature request related to a problem? Please describe.**
Svelte 5 is (mostly) backwards compatible, and as such I imagine extending support shouldn't be a major issue. At the moment, I have not been able to implement visual editing with a simple Svelte 5 application using `@sanity/svelte-loader`. I haven't attempted a setup without `svelte-loader`. 

**Describe the solution you'd like**
I'd like to be able to follow [the integration guide](https://www.sanity.io/docs/svelte-loader) and end up with a working visual editing tool. 

**Describe alternatives you've considered**
Installing with `--legacy-peer-deps`. I end up having to install react, and the implementation is too broken to work around. I end up with errors such as:

`Error: Build failed with 2 errors:
node_modules/@sanity/visual-editing/dist/_chunks-es/PointerEvents.js:1:528: ERROR: Could not resolve "react-dom"
node_modules/@sanity/visual-editing/dist/_chunks-es/renderVisualEditing.js:1:102: ERROR: Could not resolve "react-dom/client"`

**Additional context**
Svelte 5 has been the go-to production version for some time now. It would be fitting to support it, and update the docs to go along with the new support.

**Comment by rdunk** [comment] 2024-12-02 16:32
Closing as dupe of https://github.com/sanity-io/visual-editing/issues/2075.

I believe we plan on adding support soon, but as far as I'm aware Svelte 5 has only been stable for about a month or so.

Just as a point of clarification, React will stay as a dependency as it is used to render overlays regardless of the framework implementation.

**Closed by rdunk** 2024-12-02 16:32 UTC
