### ISSUE TITLE
[Presentation] Unable to open Popover Menus when a Dialog is open

### ISSUE THREAD

**Issue by thomasKn** [sanity-io/visual-editing#1120] opened 2024-03-13 22:21 UTC
**Describe the bug**

In Presentation mode, I'm unable to use some studio features when a dialog is open. I cannot open popover menus.
See the following [screencast](https://cdn.shopify.com/videos/c/o/v/d5feceb7be5d4a81bf19b4440403b70f.mp4).

At the end of the video, I'm trying to delete the image using the 3 dots button, but instead of the popover menu, an overlay to update the image appears. I also noticed that custom blocks dialogs (such as the image one) re-appears after closing.

The issue appeared since `v3.33.0`.

Also, in `v3.32.0` the dialog opens inside the pane, which is more convenient in terms of UX to see live updates in realtime.
I don't know if this is a bug or not but since `v3.33.0` the Dialog appears has a global overlay on top of the webpage which makes it hard to see live updates.

**To Reproduce**

1. Clone https://github.com/thomasKn/sanity-template-remix-clean
2. Add a new post
3. Open presentation mode and try to use portable text popover features when adding a new section

**Which versions of Sanity are you using?**

sanity `3.33.0`

**Which versions of Node.js / npm are you running?**

10.2.4
v21.6.2

**Comment by rdunk** [comment] 2024-03-13 23:26
Thank you for reporting. This looks like an issue caused by the collapsed state introduced in `v3.33.0`.

As a less than ideal workaround whilst we get a fix published, you shouldn't experience this if the pane is greater than 640px wide.

**Comment by rdunk** [comment] 2024-03-14 13:44
The fix has been committed and should appear in the next studio release. I'll leave this issue open until then. Thanks again.

**Comment by thomasKn** [comment] 2024-03-14 13:49
Thanks! I updated @sanity/presentation to `v1.11.6` and I confirm the issue has been fixed.

**Comment by rdunk** [comment] 2024-03-15 17:41
Fix also available in `sanity@3.34.0`.

**Closed by rdunk** 2024-03-15 17:41 UTC
